//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17626.
// 

using System.Xml.Serialization;

namespace PillarAPI {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class CollectionSettings {
        
        private string collectionIDField;
        
        private ProtocolSettings protocolSettingsField;
        
        private ClientSettings clientSettingsField;
        
        private PillarSettings pillarSettingsField;
        
        private DeleteFileSettings deleteFileSettingsField;
        
        private string[] getAuditTrailSettingsField;
        
        private GetChecksumsSettings getChecksumsSettingsField;
        
        private GetFileSettings getFileSettingsField;
        
        private GetFileIDsSettings getFileIDsSettingsField;
        
        private string[] getStatusSettingsField;
        
        private PutFileSettings putFileSettingsField;
        
        private ReplaceFileSettings replaceFileSettingsField;
        
        private PermissionSet permissionSetField;
        
        /// <remarks/>
        public string CollectionID {
            get {
                return this.collectionIDField;
            }
            set {
                this.collectionIDField = value;
            }
        }
        
        /// <remarks/>
        public ProtocolSettings ProtocolSettings {
            get {
                return this.protocolSettingsField;
            }
            set {
                this.protocolSettingsField = value;
            }
        }
        
        /// <remarks/>
        public ClientSettings ClientSettings {
            get {
                return this.clientSettingsField;
            }
            set {
                this.clientSettingsField = value;
            }
        }
        
        /// <remarks/>
        public PillarSettings PillarSettings {
            get {
                return this.pillarSettingsField;
            }
            set {
                this.pillarSettingsField = value;
            }
        }
        
        /// <remarks/>
        public DeleteFileSettings DeleteFileSettings {
            get {
                return this.deleteFileSettingsField;
            }
            set {
                this.deleteFileSettingsField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("ContributorIDs", IsNullable=false)]
        public string[] GetAuditTrailSettings {
            get {
                return this.getAuditTrailSettingsField;
            }
            set {
                this.getAuditTrailSettingsField = value;
            }
        }
        
        /// <remarks/>
        public GetChecksumsSettings GetChecksumsSettings {
            get {
                return this.getChecksumsSettingsField;
            }
            set {
                this.getChecksumsSettingsField = value;
            }
        }
        
        /// <remarks/>
        public GetFileSettings GetFileSettings {
            get {
                return this.getFileSettingsField;
            }
            set {
                this.getFileSettingsField = value;
            }
        }
        
        /// <remarks/>
        public GetFileIDsSettings GetFileIDsSettings {
            get {
                return this.getFileIDsSettingsField;
            }
            set {
                this.getFileIDsSettingsField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("ContributorIDs", IsNullable=false)]
        public string[] GetStatusSettings {
            get {
                return this.getStatusSettingsField;
            }
            set {
                this.getStatusSettingsField = value;
            }
        }
        
        /// <remarks/>
        public PutFileSettings PutFileSettings {
            get {
                return this.putFileSettingsField;
            }
            set {
                this.putFileSettingsField = value;
            }
        }
        
        /// <remarks/>
        public ReplaceFileSettings ReplaceFileSettings {
            get {
                return this.replaceFileSettingsField;
            }
            set {
                this.replaceFileSettingsField = value;
            }
        }
        
        /// <remarks/>
        public PermissionSet PermissionSet {
            get {
                return this.permissionSetField;
            }
            set {
                this.permissionSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class ProtocolSettings {
        
        private string defaultChecksumTypeField;
        
        private string allowedFileIDPatternField;
        
        private bool requireMessageAuthenticationField;
        
        private bool requireOperationAuthorizationField;
        
        private bool requireChecksumForDestructiveRequestsField;
        
        private bool requireChecksumForNewFileRequestsField;
        
        private string collectionDestinationField;
        
        private string alarmDestinationField;
        
        private MessageBusConfiguration messageBusConfigurationField;
        
        /// <remarks/>
        public string DefaultChecksumType {
            get {
                return this.defaultChecksumTypeField;
            }
            set {
                this.defaultChecksumTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AllowedFileIDPattern {
            get {
                return this.allowedFileIDPatternField;
            }
            set {
                this.allowedFileIDPatternField = value;
            }
        }
        
        /// <remarks/>
        public bool RequireMessageAuthentication {
            get {
                return this.requireMessageAuthenticationField;
            }
            set {
                this.requireMessageAuthenticationField = value;
            }
        }
        
        /// <remarks/>
        public bool RequireOperationAuthorization {
            get {
                return this.requireOperationAuthorizationField;
            }
            set {
                this.requireOperationAuthorizationField = value;
            }
        }
        
        /// <remarks/>
        public bool RequireChecksumForDestructiveRequests {
            get {
                return this.requireChecksumForDestructiveRequestsField;
            }
            set {
                this.requireChecksumForDestructiveRequestsField = value;
            }
        }
        
        /// <remarks/>
        public bool RequireChecksumForNewFileRequests {
            get {
                return this.requireChecksumForNewFileRequestsField;
            }
            set {
                this.requireChecksumForNewFileRequestsField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionDestination {
            get {
                return this.collectionDestinationField;
            }
            set {
                this.collectionDestinationField = value;
            }
        }
        
        /// <remarks/>
        public string AlarmDestination {
            get {
                return this.alarmDestinationField;
            }
            set {
                this.alarmDestinationField = value;
            }
        }
        
        /// <remarks/>
        public MessageBusConfiguration MessageBusConfiguration {
            get {
                return this.messageBusConfigurationField;
            }
            set {
                this.messageBusConfigurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class MessageBusConfiguration {
        
        private string nameField;
        
        private string uRLField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    public partial class OperationPermission {
        
        private Operation operationField;
        
        private string[] allowedComponentsField;
        
        /// <remarks/>
        public Operation Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("IDs", IsNullable=false)]
        public string[] AllowedComponents {
            get {
                return this.allowedComponentsField;
            }
            set {
                this.allowedComponentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    public enum Operation {
        
        /// <remarks/>
        GetFile,
        
        /// <remarks/>
        PutFile,
        
        /// <remarks/>
        GetChecksums,
        
        /// <remarks/>
        GetFileIDs,
        
        /// <remarks/>
        DeleteFile,
        
        /// <remarks/>
        ReplaceFile,
        
        /// <remarks/>
        GetAuditTrails,
        
        /// <remarks/>
        GetStatus,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    public partial class Certificate {
        
        private byte[] certificateDataField;
        
        private string[] allowedCertificateUsersField;
        
        /// <remarks/>
        [XmlElement(DataType="base64Binary")]
        public byte[] CertificateData {
            get {
                return this.certificateDataField;
            }
            set {
                this.certificateDataField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("IDs", IsNullable=false)]
        public string[] AllowedCertificateUsers {
            get {
                return this.allowedCertificateUsersField;
            }
            set {
                this.allowedCertificateUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class ClientSettings {
        
        private string identificationTimeoutField;
        
        private string operationTimeoutField;
        
        private string[] pillarIDsField;
        
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string IdentificationTimeout {
            get {
                return this.identificationTimeoutField;
            }
            set {
                this.identificationTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string OperationTimeout {
            get {
                return this.operationTimeoutField;
            }
            set {
                this.operationTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("PillarIDs")]
        public string[] PillarIDs {
            get {
                return this.pillarIDsField;
            }
            set {
                this.pillarIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class PillarSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class DeleteFileSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class GetChecksumsSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class GetFileSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class GetFileIDsSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class PutFileSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class ReplaceFileSettings {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class PermissionSet {
        
        private Permission[] permissionField;
        
        /// <remarks/>
        [XmlElement("Permission")]
        public Permission[] Permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class Permission {
        
        private string descriptionField;
        
        private Certificate certificateField;
        
        private InfrastructurePermission[] infrastructurePermissionField;
        
        private OperationPermission[] operationPermissionField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Certificate Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("InfrastructurePermission")]
        public InfrastructurePermission[] InfrastructurePermission {
            get {
                return this.infrastructurePermissionField;
            }
            set {
                this.infrastructurePermissionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("OperationPermission")]
        public OperationPermission[] OperationPermission {
            get {
                return this.operationPermissionField;
            }
            set {
                this.operationPermissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    public enum InfrastructurePermission {
        
        /// <remarks/>
        MessageBusClient,
        
        /// <remarks/>
        MessageBusServer,
        
        /// <remarks/>
        FileExchangeClient,
        
        /// <remarks/>
        FileExchangeServer,
        
        /// <remarks/>
        MessageSigner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class GetAuditTrailSettings {
        
        private string[] contributorIDsField;
        
        /// <remarks/>
        [XmlElement("ContributorIDs")]
        public string[] ContributorIDs {
            get {
                return this.contributorIDsField;
            }
            set {
                this.contributorIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17626")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://bitrepository.org/settings/CollectionSettings.xsd")]
    [XmlRoot(Namespace="http://bitrepository.org/settings/CollectionSettings.xsd", IsNullable=false)]
    public partial class GetStatusSettings {
        
        private string[] contributorIDsField;
        
        /// <remarks/>
        [XmlElement("ContributorIDs")]
        public string[] ContributorIDs {
            get {
                return this.contributorIDsField;
            }
            set {
                this.contributorIDsField = value;
            }
        }
    }
}
