//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pillar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pillar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle felter skal udfyldes..
        /// </summary>
        internal static string Fill_all_fields {
            get {
                return ResourceManager.GetString("Fill_all_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diskspace må kun indeholde heltal, max: 9223372036854775807.
        /// </summary>
        internal static string only_Int64 {
            get {
                return ResourceManager.GetString("only_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillaren er ikke aktiv!.
        /// </summary>
        internal static string pillar_off {
            get {
                return ResourceManager.GetString("pillar_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillar kører.
        /// </summary>
        internal static string pillar_on {
            get {
                return ResourceManager.GetString("pillar_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row deleted!.
        /// </summary>
        internal static string row_deleted {
            get {
                return ResourceManager.GetString("row_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row inserted!.
        /// </summary>
        internal static string Row_inserted {
            get {
                return ResourceManager.GetString("Row_inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row NOT deleted..
        /// </summary>
        internal static string row_not_deleted {
            get {
                return ResourceManager.GetString("row_not_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row NOT inserted..
        /// </summary>
        internal static string Row_NOT_inserted {
            get {
                return ResourceManager.GetString("Row_NOT_inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row NOT updated..
        /// </summary>
        internal static string row_not_updated {
            get {
                return ResourceManager.GetString("row_not_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row updated!.
        /// </summary>
        internal static string row_updated {
            get {
                return ResourceManager.GetString("row_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der findes allerede en user med pågældende collectionID.
        /// </summary>
        internal static string user_exists {
            get {
                return ResourceManager.GetString("user_exists", resourceCulture);
            }
        }
    }
}
